# Generated by Django 4.2.27 on 2025-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jaishaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_ser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
